Dev 1854 implement open source verificator design
AkarionDevelopers/open-data-integrity-verification pull request #3
Opened 2021-11-17 12:55 UTC by martinpam

2021-11-18 09:17 UTC, paul-em requested changes

2021-11-18 09:17 UTC, paul-em commented on app/index.js
> +      $fileList.innerHTML += $html;
This is a potential security risk. using innerHtml can lead to xss attacks. Please sanitize the user defined output in line 179 with this function:

```
function sanitizeHTML(text) {
  const element = document.createElement('div');
  element.innerText = text;
  return element.innerHTML;
}
```

2021-11-18 09:17 UTC, paul-em commented on app/verify.js
> +  return hashRaw(cumulatedHash);
Remove the whitespace please :) are you using any linter?

2021-11-18 09:42 UTC, martinpam commented on app/verify.js
> +  return hashRaw(cumulatedHash);
activated format on save now, so no more whitespaces from here on out :D (probably)

2021-11-18 09:48 UTC, paul-em requested changes
Oh no, your autoformat changed single quotes to double quotes 😱  you can edit this setting in your editor. We only use single quotes.

Also for future reference: If you do a format commit, do not add any other changes in there as it is impossible to find them and review them 😆

2021-11-22 16:14 UTC, paul-em approved these changes

2021-11-22 16:39 UTC, merged