DEV-3429 Show all object data in a pragmatic way; Doing proper reset
AkarionDevelopers/open-data-integrity-verification pull request #6
Opened 2023-01-10 14:17 UTC by Martin01248

I assume there is no review app
but this code changes are already live.
See here
https://akariondevelopers.github.io/open-data-integrity-verification/

Here are 2 notarization PDFs for testing

[Feuer-notarization (2).pdf](https://github.com/AkarionDevelopers/open-data-integrity-verification/files/10383469/Feuer-notarization.2.pdf)
[Korruptionsverdacht bei Vice-Direktorin Marlie Muster-notarization (1).pdf](https://github.com/AkarionDevelopers/open-data-integrity-verification/files/10383470/Korruptionsverdacht.bei.Vice-Direktorin.Marlie.Muster-notarization.1.pdf)

Before
![Screenshot 2023-01-10 at 15 07 29](https://user-images.githubusercontent.com/78416724/211574979-4eb1197c-6516-4f17-8893-7e10be13fde2.png)

After
![Screenshot 2023-01-10 at 15 08 24](https://user-images.githubusercontent.com/78416724/211575034-51de556d-4703-41fb-bbc0-366eccdf3bfd.png)

2023-01-10 14:20 UTC, Martin01248 commented on app/index.js
> +  data.set('isVerified', []);
I found this bug.
Reset was not properly done.
Before 2nd notarization showed data from 1st one.
Now it shows correct data.

2023-01-11 10:49 UTC, manuelmeindl requested changes
just a small finding, rest looks fine!

2023-01-11 10:49 UTC, manuelmeindl commented on app/helper.js
> +  if (objectData == null || objectData.length === 0) {
comparisons in JS should always be done with three === so the type is also considered.

2023-01-11 13:05 UTC, Martin01248 commented on app/helper.js
> +  if (objectData == null || objectData.length === 0) {
Fixed

2023-01-11 13:08 UTC, manuelmeindl approved these changes

2023-01-11 15:48 UTC, merged